logging:
  base:
    debug: false
  modules:
    log_storage.logserver:
      debug: false
    log_collection.collector:
      debug: false
    log_collection.batch_handler:
      debug: false
    log_filtering.prefilter:
      debug: false
    data_inspection.inspector:
      debug: false
    data_analysis.detector:
      debug: false

pipeline:
  log_storage:
    logserver:
      input_file: "/opt/file.txt"

  log_collection:
    collector:
      logline_format:
        - [ "timestamp", Timestamp, "%Y-%m-%dT%H:%M:%S.%fZ" ]
        - [ "status_code", ListItem, [ "NOERROR", "NXDOMAIN" ], [ "NXDOMAIN" ] ]
        - [ "client_ip", IpAddress ]
        - [ "dns_server_ip", IpAddress ]
        - [ "domain_name", RegEx, '^(?=.{1,253}$)((?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+[A-Za-z]{2,63}$' ]
        - [ "record_type", ListItem, [ "A", "AAAA" ] ]
        - [ "response_ip", IpAddress ]
        - [ "size", RegEx, '^\d+b$' ]
    batch_handler:
      batch_size: 10000
      batch_timeout: 30.0
      subnet_id:
        ipv4_prefix_length: 24
        ipv6_prefix_length: 64

  data_inspection:
    inspector:
      mode: univariate # multivariate, ensemble
      # Only used when mode is set to ensemble
      ensemble:
        model: WeightEnsemble
        module: streamad.process
        model_args:
      models:
        - model: ZScoreDetector
          module: streamad.model
          model_args:
            is_global: false
      anomaly_threshold: 0.01
      score_threshold: 0.5
      time_type: ms
      time_range: 20

  data_analysis:
    detector:
      model: rf # XGBoost
      checksum: ba1f718179191348fe2abd51644d76191d42a5d967c6844feb3371b6f798bf06
      base_url: https://heibox.uni-heidelberg.de/d/0d5cbcbe16cd46a58021/
      threshold: 0.5

  monitoring:
    clickhouse_connector:
      batch_size: 50  # do not set higher
      batch_timeout: 2.0

environment:
  kafka_brokers:
    - hostname: kafka1
      port: 8097
    - hostname: kafka2
      port: 8098
    - hostname: kafka3
      port: 8099
  kafka_topics:
    pipeline:
      logserver_in: "pipeline-logserver_in"
      logserver_to_collector: "pipeline-logserver_to_collector"
      batch_sender_to_prefilter: "pipeline-batch_sender_to_prefilter"
      prefilter_to_inspector: "pipeline-prefilter_to_inspector"
      inspector_to_detector: "pipeline-inspector_to_detector"
  monitoring:
    clickhouse_server:
      hostname: clickhouse-server
