FROM python:3.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY requirements/requirements.logserver.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile  -r requirements.logserver.txt

COPY src/base ./src/base
COPY src/logserver ./src/logserver
COPY config.yaml .

RUN rm -rf /root/.cache

CMD [ "python", "src/logserver/server.py"]
