FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY requirements/requirements.detector.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile -r requirements.detector.txt

COPY src/base ./src/base
COPY src/detector ./src/detector
COPY config.yaml .

RUN rm -rf /root/.cache

CMD [ "python", "src/detector/detector.py"]
