FROM python:3

WORKDIR /usr/src/app

COPY requirements/requirements.detector.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile  -r requirements.detector.txt

COPY src/base ./src/base
COPY src/detector ./src/detector
COPY config.yaml .

CMD [ "python", "src/detector/analyzer.py"]
