FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY requirements/requirements.monitoring.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile -r requirements.monitoring.txt

COPY src/base ./src/base
COPY src/monitoring ./src/monitoring
COPY config.yaml .

RUN rm -rf /root/.cache

CMD [ "python", "src/monitoring/monitoring_agent.py"]
