FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY requirements/requirements.logcollector.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile -r requirements.logcollector.txt

COPY src/base ./src/base
COPY src/logcollector ./src/logcollector
COPY config.yaml .

RUN rm -rf /root/.cache

CMD [ "python", "src/logcollector/collector.py"]
