FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

RUN pip --disable-pip-version-check install --no-cache-dir --no-compile clickhouse_connect

COPY src/base ./src/base
COPY config.yaml .

RUN rm -rf /root/.cache

CMD [ "python", "docker/dev-query.py"]
