services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    container_name: clickhouse-server
    volumes:
      - ../../create_tables:/docker-entrypoint-initdb.d
      - ch_data:/var/lib/clickhouse/
      - ch_logs:/var/log/clickhouse-server/
    networks:
      - heidgaf
    restart: "unless-stopped"
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 8123" ]
      interval: 10s
      timeout: 5s
      retries: 3
