FROM python:3

WORKDIR /usr/src/app

COPY requirements.inspector.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile  -r requirements.inspector.txt

COPY heidgaf_core ./heidgaf_core
COPY heidgaf_inspection ./heidgaf_inspection
COPY config.yaml .

CMD [ "python", "heidgaf_inspection/inspector.py"]
