FROM python:3

WORKDIR /usr/src/app

COPY requirements.prefilter.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile  -r requirements.prefilter.txt

COPY src/base ./src/base
COPY src/prefilter ./src/prefilter
COPY config.yaml .

CMD [ "python", "src/prefilter/prefilter.py"]
