FROM python:3

WORKDIR /usr/src/app

COPY requirements.logcollector.txt ./
RUN pip --disable-pip-version-check install --no-cache-dir --no-compile  -r requirements.logcollector.txt

COPY src/base ./src/base
COPY src/logcollector ./src/logcollector
COPY config.yaml .

CMD [ "python", "src/logcollector/collector.py"]
