services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.12.75-alpine
    volumes:
      - ../create_tables:/docker-entrypoint-initdb.d
    networks:
      - heidgaf
    ports:
      - "8123:8123"
      - "9000:9000"
#    healthcheck:
#      test: [ "CMD-SHELL", "nc -z localhost 8123" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
    deploy:
      placement:
        constraints: [ node.hostname == heidgaf-3 ]
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:11.2.2-security-01
    networks:
      - heidgaf
    ports:
      - "3000:3000"
    volumes:
      - ../grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana-provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../grafana-provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
#    healthcheck:
#      test: [ "CMD-SHELL", "nc -z localhost 3000" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
    deploy:
      placement:
        constraints: [ node.hostname == heidgaf-3 ]
      restart_policy:
        condition: on-failure

  monitoring_agent:
    image: stefan96/heidgaf-monitoring
    networks:
      - heidgaf
    environment:
      - GROUP_ID=monitoring_agent
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - clickhouse-server
    deploy:
      placement:
        constraints: [ node.hostname == heidgaf-3 ]
      restart_policy:
        condition: on-failure

networks:
  heidgaf:
    external: true
