{
 "title": "Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Granularity",
    "query": "SELECT CASE \n    WHEN (dateDiff('minute', toDateTime($__fromTime), toDateTime($__toTime))) <= 5 THEN 'Second'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 1 THEN 'Minute'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 24 THEN 'Hour'\n    ELSE 'Day'\nEND AS interval;"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest 100 Malicious IP Addresses and their Host Names",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT client_ip, arrayStringConcat(JSONExtract(domain_names, 'Array(String)'), ', ') AS domain_list\nFROM alerts\nWHERE alert_timestamp >= $__fromTime AND alert_timestamp <= $__toTime\nORDER BY alert_timestamp DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Alerts per Time",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOf${Granularity}(toDateTime64(alert_timestamp, 6)) AS time_bucket,\n    count(client_ip) AS \"count\"\nFROM alerts\nWHERE alert_timestamp >= toStartOf${Granularity}(toDateTime64($__fromTime, 6)) AND alert_timestamp <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket\nWITH FILL\nFROM toStartOf${Granularity}(toDateTime64($__fromTime, 6))\nTO toStartOf${Granularity}(toDateTime64($__toTime, 6))\nSTEP toInterval${Granularity}(1);"
    }
   ]
  },
  {
   "title": "Number of Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM (\n  SELECT DISTINCT client_ip\n  FROM alerts\n  WHERE alert_timestamp >= $__fromTime AND alert_timestamp <= $__toTime\n);"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 } }
 ]
}