{
 "title": "Log Volumes",
 "time": { "from": "2025-01-13T08:23:10.007Z", "to": "2025-01-13T08:24:20.039Z" },
 "templating": {
  "list": [
   {
    "name": "Granularity",
    "query": "SELECT CASE \n    WHEN (dateDiff('minute', toDateTime($__fromTime), toDateTime($__toTime))) <= 5 THEN 'Second'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 1 THEN 'Minute'\n    WHEN (dateDiff('hour', toDateTime($__fromTime), toDateTime($__toTime))) <= 24 THEN 'Hour'\n    ELSE 'Day'\nEND AS interval;"
   },
   {
    "name": "include_modules",
    "label": "Include Modules",
    "query": "LogServer : 'LogServer', Collector : 'Collector', BatchHandler : 'BatchHandler', Prefilter : 'Prefilter', Inspector : 'Inspector', Detector : 'Detector'"
   }
  ]
 },
 "panels": [
  {
   "title": "Received Log Lines in LogServer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM server_logs sl\nFULL OUTER JOIN server_logs_timestamps slt\nON sl.message_id = slt.message_id"
    },
    {
     "rawSql": "SELECT count(*)\nFROM server_logs sl"
    },
    {
     "rawSql": "SELECT count(*)\nFROM dns_loglines\n\nUNION ALL \n\nSELECT count(*)\nFROM failed_dns_loglines"
    },
    {
     "rawSql": "SELECT count(*)\nFROM server_logs_timestamps slt"
    }
   ]
  },
  {
   "title": "Maximum Batch Size for Configured Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(entry_count)\nFROM fill_levels\nWHERE stage = 'log_collection.batch_handler'\n  AND entry_type = 'total_loglines_in_batches'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Fill States Combined (logarithmic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'log_collection.collector'\n  AND 'Collector' IN (${include_modules:csv})\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    },
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'log_filtering.prefilter'\n  AND entry_type = 'total_loglines'\n  AND 'Prefilter' IN (${include_modules:csv})\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    },
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'data_inspection.inspector'\n  AND entry_type = 'total_loglines'\n  AND 'Inspector' IN (${include_modules:csv})\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    },
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'data_analysis.detector'\n  AND entry_type = 'total_loglines'\n  AND 'Detector' IN (${include_modules:csv})\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    },
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'log_collection.batch_handler'\n  AND entry_type = 'total_loglines_in_batches'\n  AND 'BatchHandler' IN (${include_modules:csv})\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Fill State Comparison",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM (\n  SELECT 'Collector' AS name, median(value) AS \"Median\", 2 AS sort_order\n  FROM (\n    SELECT entry_count as value\n    FROM fill_levels\n    WHERE stage = 'log_collection.collector' AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n  )\n\n  UNION ALL\n\n  SELECT 'BatchHandler' AS name, median(value) AS \"Median\", 3 AS sort_order\n  FROM (\n    SELECT entry_count as value\n    FROM fill_levels\n    WHERE stage = 'log_collection.batch_handler' AND entry_type = 'total_loglines_in_batches' AND\n          timestamp >= $__fromTime AND timestamp <= $__toTime\n  )\n\n  UNION ALL\n\n  SELECT 'Prefilter' AS name, median(value) AS \"Median\", 4 AS sort_order\n  FROM (\n    SELECT entry_count as value\n    FROM fill_levels\n    WHERE stage = 'log_filtering.prefilter' AND entry_type = 'total_loglines' AND\n          timestamp >= $__fromTime AND timestamp <= $__toTime\n  )\n\n  UNION ALL\n\n  SELECT 'Inspector' AS name, median(value) AS \"Median\", 5 AS sort_order\n  FROM (\n    SELECT entry_count as value\n    FROM fill_levels\n    WHERE stage = 'data_inspection.inspector' AND entry_type = 'total_loglines' AND\n          timestamp >= $__fromTime AND timestamp <= $__toTime\n  )\n\n  UNION ALL\n\n  SELECT 'Detector' AS name, median(value) AS \"Median\", 6 AS sort_order\n  FROM (\n    SELECT entry_count as value\n    FROM fill_levels\n    WHERE stage = 'data_analysis.detector' AND entry_type = 'total_loglines' AND\n          timestamp >= $__fromTime AND timestamp <= $__toTime\n  )\n)\nWHERE name IN (${include_modules:csv})\nORDER BY sort_order ASC;"
    }
   ]
  },
  { "title": "Number of Log Lines per Module", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Collector Fill State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM fill_levels\nWHERE stage = 'log_collection.collector'\n  AND entry_type = 'total_loglines'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'log_collection.collector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "title": "Prefilter Fill State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM fill_levels\nWHERE stage = 'log_filtering.prefilter'\n  AND entry_type = 'total_loglines'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'log_filtering.prefilter'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'log_collection.collector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'log_filtering.prefilter'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "title": "BatchHandler Fill State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'log_collection.batch_handler'\n  AND entry_type = 'total_loglines_in_batches'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    },
    {
     "rawSql": "SELECT timestamp, entry_count AS \" \"\nFROM fill_levels\nWHERE stage = 'log_collection.batch_handler'\n  AND entry_type = 'total_loglines_in_buffer'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Batch Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'log_collection.batch_handler'\n      AND entry_type = 'total_loglines_in_batches'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Buffer Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'log_collection.batch_handler'\n      AND entry_type = 'total_loglines_in_buffer'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "title": "Inspector Fill State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM fill_levels\nWHERE stage = 'data_inspection.inspector'\n  AND entry_type = 'total_loglines'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'data_inspection.inspector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'log_collection.batch_handler'\n      AND entry_type = 'total_loglines_in_batches'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    },
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'log_collection.batch_handler'\n      AND entry_type = 'total_loglines_in_buffer'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'data_inspection.inspector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "title": "Detector Fill State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM fill_levels\nWHERE stage = 'data_analysis.detector'\n  AND entry_type = 'total_loglines'\n  AND timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT median(entry_count) AS \"Median\"\nFROM (\n      SELECT *\n      FROM fill_levels\n      WHERE stage = 'data_analysis.detector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(value) AS \"Minimum\", avg(value) AS \"Average\", max(value) AS \"Maximum\"\nFROM (\n      SELECT entry_count AS value\n      FROM fill_levels\n      WHERE stage = 'data_analysis.detector'\n      AND entry_type = 'total_loglines'\n      AND timestamp >= $__fromTime AND timestamp <= $__toTime\n)"
    }
   ]
  },
  {
   "title": "Old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "TODO: How many have existed in what stage",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT *\nFROM (\n      SELECT 'Suspicious' AS state, MIN(message_count) AS minimal_size, AVG(message_count) AS average_size, MAX(message_count) AS maximal_size, 3 as sort_order\n      FROM suspicious_batch_timestamps\n      WHERE stage = 'data_inspection.inspector' AND\n            status = 'finished'\n\n      UNION ALL\n\n      SELECT 'Filtered' AS state, MIN(message_count) AS minimal_size, AVG(message_count) AS average_size, MAX(message_count) AS maximal_size, 2 as sort_order\n      FROM batch_timestamps\n      WHERE stage = 'log_filtering.prefilter' AND\n            status = 'finished'\n\n      UNION ALL\n\n      SELECT 'Initial' AS state, MIN(message_count) AS minimal_size, AVG(message_count) AS average_size, MAX(message_count) AS maximal_size, 1 as sort_order\n      FROM batch_timestamps\n      WHERE stage = 'log_collection.batch_handler' AND\n            status = 'completed'\n)\nORDER BY sort_order ASC;"
      }
     ]
    },
    {
     "title": "Number of Incoming Lines per $Granularity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n    toStartOf${Granularity}(timestamp_in) AS time_bucket,\n    count(*) AS lines\nFROM failed_dns_loglines\nWHERE timestamp_in >= $__fromTime AND timestamp_in <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket;"
      },
      {
       "rawSql": "SELECT \n    toStartOf${Granularity}(timestamp) AS time_bucket,\n    count(*) AS lines\nFROM logline_timestamps\nWHERE stage = 'log_collection.collector' AND\n      status = 'in_process' AND\n      timestamp >= $__fromTime AND timestamp <= $__toTime\nGROUP BY time_bucket\nORDER BY time_bucket;"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time in BatchHandler (with waiting time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "rawSql": "SELECT lt2.timestamp as time, dateDiff('microsecond', lt1.timestamp, lt2.timestamp) AS diff\nFROM logline_timestamps lt1\nINNER JOIN logline_to_batches ltb ON lt1.logline_id = ltb.logline_id\nINNER JOIN batch_timestamps lt2 ON ltb.batch_id = lt2.batch_id\nWHERE lt1.stage = 'log_collection.batch_handler' AND lt1.status = 'in_process' AND\n      lt2.stage = 'log_collection.batch_handler' AND lt2.status = 'completed' AND\n      lt1.timestamp >= $__fromTime AND lt2.timestamp <= $__toTime\nORDER BY time ASC;"
      }
     ]
    },
    {
     "title": "Invalid DNS Log Lines per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 41 },
     "targets": [
      {
       "rawSql": "SELECT timestamps_per_second as \"time\", count(*) / count(DISTINCT timestamps_per_second) AS number_per_second\nFROM failed_dns_loglines\nGROUP BY date_trunc('second', timestamp_failed) AS timestamps_per_second, time\nORDER BY time ASC;\n"
      }
     ]
    },
    {
     "title": "Time in the Collector",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "rawSql": "SELECT t1.timestamp as time, dateDiff('microsecond', t1.timestamp, t2.timestamp) as time_in_module, median(time_in_module) OVER () AS median_line\nFROM logline_timestamps t1, logline_timestamps t2\nWHERE t1.logline_id = t2.logline_id AND\n      t1.status = 'in_process' AND t2.status = 'finished' AND\n      t1.stage = 'log_collection.collector' AND t2.stage = 'log_collection.collector' AND\n      time >= $__fromTime AND time <= $__toTime\nORDER BY time ASC;"
      }
     ]
    },
    {
     "title": "Average percentage of relevant log lines per Batch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT batch_id, (t2.message_count / t1.message_count) AS relevant_loglines\nFROM batch_timestamps t1, batch_timestamps t2\nWHERE t1.batch_id = t2.batch_id AND\n      t1.stage = 'log_filtering.prefilter' AND\n      t2.stage = 'log_filtering.prefilter' AND\n      t1.status = 'in_process' AND\n      (t2.status = 'finished' OR t2.status = 'filtered_out')\nGROUP BY batch_id, t1.message_count, t2.message_count"
      }
     ]
    },
    {
     "title": "Average LogServer Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 18, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT timestamp_in AS time, dateDiff(microsecond, timestamp_in, event_timestamp) AS values\nFROM server_logs, server_logs_timestamps\nWHERE server_logs.message_id = server_logs_timestamps.message_id AND \n      event = 'timestamp_out' AND\n      time >= $__fromTime AND time <= $__toTime\nGROUP BY message_id, timestamp_in, event_timestamp\nORDER BY time ASC;\n"
      }
     ]
    },
    {
     "title": "Average Collector Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.timestamp as time, dateDiff('microsecond', t1.timestamp, t2.timestamp) as values\nFROM logline_timestamps t1, logline_timestamps t2\nWHERE t1.logline_id = t2.logline_id AND\n      t1.status = 'in_process' AND t2.status = 'finished' AND\n      t1.stage = 'log_collection.collector' AND t2.stage = 'log_collection.collector' AND\n      time >= $__fromTime AND time <= $__toTime\nORDER BY time ASC;"
      }
     ]
    },
    {
     "title": "Average Prefilter Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT t1.timestamp as time, dateDiff('microsecond', t1.timestamp, t2.timestamp) as values\nFROM batch_timestamps t1, batch_timestamps t2\nWHERE t1.batch_id = t2.batch_id AND\n      t1.status = 'in_process' AND t2.status = 'finished' AND\n      t1.stage = 'log_filtering.prefilter' AND t2.stage = 'log_filtering.prefilter' AND\n      time >= $__fromTime AND time <= $__toTime\nORDER BY time ASC;"
      }
     ]
    },
    {
     "title": "Time in the LogServer",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "rawSql": "SELECT timestamp_in AS time, dateDiff(microsecond, timestamp_in, event_timestamp) AS time_in_module, median(time_in_module) OVER () AS median_line\nFROM server_logs, server_logs_timestamps\nWHERE server_logs.message_id = server_logs_timestamps.message_id AND \n      event = 'timestamp_out' AND\n      time >= $__fromTime AND time <= $__toTime\nGROUP BY message_id, timestamp_in, event_timestamp\nORDER BY time ASC;\n"
      }
     ]
    },
    {
     "title": "Average Inspector Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT bt2.timestamp AS time, dateDiff('microsecond', bt1.timestamp, bt2.timestamp) AS values\nFROM batch_timestamps bt1\nINNER JOIN batch_timestamps bt2 ON bt1.batch_id = bt2.batch_id\nWHERE bt1.batch_id = bt2.batch_id AND bt1.stage = 'data_inspection.inspector' AND bt1.status = 'in_process' AND\n      bt2.stage = 'data_inspection.inspector' AND bt2.is_active = False AND\n      bt1.timestamp >= $__fromTime AND bt2.timestamp <= $__toTime\nORDER BY time ASC\n\nUNION ALL\n\nSELECT sbt.timestamp AS time, dateDiff('microsecond', bt.timestamp, sbt.timestamp) AS values\nFROM batch_timestamps bt\nINNER JOIN suspicious_batches_to_batch sbtb ON bt.batch_id = sbtb.batch_id\nINNER JOIN suspicious_batch_timestamps sbt ON sbtb.suspicious_batch_id = sbt.suspicious_batch_id\nWHERE bt.stage = 'data_inspection.inspector' AND bt.status = 'in_process' AND\n      sbt.stage = 'data_inspection.inspector' AND sbt.status = 'finished' AND\n      bt.timestamp >= $__fromTime AND sbt.timestamp <= $__toTime\nORDER BY time ASC"
      }
     ]
    }
   ]
  }
 ]
}