services:
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    command: ["--kafka.server=kafka1:8097", "--kafka.server=kafka2:8098", "--kafka.server=kafka3:8099"]
    networks:
      - heidgaf
networks:
  heidgaf:
    external: true
