services:
  monitoring_agent:
    # build:
    #   context: ../../..
    #   dockerfile: docker/dockerfiles/Dockerfile.monitoring
    #   network: host
    image: stefan96/heidgaf-monitoring:v1.0.0
    restart: "unless-stopped"
    # platform: linux/x86_64
    volumes:
      - ../../../config.yaml:/app/config.yaml
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      grafana:
        condition: service_healthy
    networks:
      - heidgaf
    environment:
      - GROUP_ID=monitoring_agent
