FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

RUN pip --disable-pip-version-check install --no-cache-dir --no-compile marshmallow_dataclass colorlog pyYAML confluent_kafka numpy polars scikit-learn torch

COPY src/base ./src/base
COPY src/train ./src/train
COPY config.yaml .
COPY benchmarking/src ./benchmarking/src
COPY benchmarking/benchmark_test_config.yaml ./benchmarking/benchmark_test_config.yaml
COPY data ./data

RUN rm -rf /root/.cache

CMD [ "python", "benchmarking/src/test_types/ramp_up_test.py"]
